### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by Eshpelin** [justicesuh/faking-contributions#6]
While running this on Python 3+, users face a very small issue where on Line 43 and 57, the code contains deprecated Python 2 syntax (no brackets used to be necessary to print before) - which makes the whole thing break. This can be easily fixed by replacing those with the following line:

Line 43 and 57 in faking-contributions.py

`				print ('Committing ' + complete)`

**Comment by justicesuh** [comment]
When I originally created this I chose to only support Python 2.  I'll probably add Python 3 support at some point.

**Comment by justicesuh** [comment]
fixed by #8
